---
# Disable line length rule because Docker lines commonly exceed the line length.
# yamllint disable rule:line-length

################################################################################
# Begin Docker Compose
################################################################################
# Project name needs to be unique for all services. While "${CLIENT}-${PROJECT}" is unique for client services,
# it's not unique for apps on a server. Service name needs to be included to make it unique. That also means
# the container name needs to be defined to prevent duplicate "service" names.
# https://docs.docker.com/compose/compose-file/04-version-and-name/
# Format: (<client>-)<server>-<project>-<service>
name: bootstrap-init-niceguyit-nebula

services:
  nebula:
    # The default "container_name" docker uses: <project>-<service>-<index>
    container_name: niceguyit-nebula
    volumes:
      - nebula-config:/config

volumes:
  nebula-config:
    external: true
